export const resultCopy = {
  en: {
    heading: "Findings", biology: "Conditions and biology", loading: "Loading recorded contacts and resources…", unavailable: "Additional records could not be loaded.",
    direct: "Names this diagnosis", related: "Related scope", broad: "Umbrella scope", observed: "Recorded dataset relation", inferred: "Inferred dataset relation", hypothesis: "Proposed dataset link",
    source: "Source", evidence: "Evidence", details: "Details", explore: "Explore connections", brief: "Create free brief", more: "More findings", less: "Show fewer", contact: "Contact", study: "View study", resource: "Request resource", paper: "Open paper", official: "Official page", route: "Recorded access route",
    scope: "Recorded for", comparison: "Shared mechanisms and differences", shared: "Shared terms", differences: "Evidence of differences", support: "People and support", resources: "Studies, resources and funding", gaps: "Missing evidence", unknown: "Not recorded", checked: "Retrieved", status: "Recorded status", holder: "Holder", role: "Role", affiliation: "Affiliation", sponsor: "Sponsor", country: "Country", year: "Year", journal: "Journal", access: "Access", licence: "Licence", mechanism: "Mechanism", biomarker: "Biomarker", symptom: "Symptom", funding: "View funding", experiment: "Prepare a shared experiment brief", relatedSupport: "Related support", order: "Returned records", noRanking: "Result position alone does not establish mechanism strength, unmet need or resource access.", empty: "No actionable records were returned for this scope.", reuse: "Reuse needs confirmation of fit, permissions and validation.", viewResource: "View resource",
  },
  de: {
    heading: "Ergebnisse", biology: "Erkrankungen und Biologie", loading: "Erfasste Kontakte und Ressourcen werden geladen…", unavailable: "Weitere Datensätze konnten nicht geladen werden.",
    direct: "Nennt diese Diagnose", related: "Verwandter Bezug", broad: "Übergreifender Bezug", observed: "Erfasste Datenbeziehung", inferred: "Abgeleitete Datenbeziehung", hypothesis: "Vorgeschlagene Datenverbindung",
    source: "Quelle", evidence: "Belege", details: "Details", explore: "Verbindungen erkunden", brief: "Kostenlosen Entwurf erstellen", more: "Weitere Ergebnisse", less: "Weniger anzeigen", contact: "Kontakt", study: "Studie ansehen", resource: "Ressource anfragen", paper: "Publikation öffnen", official: "Offizielle Seite", route: "Erfasster Zugangsweg",
    scope: "Erfasst für", comparison: "Gemeinsame Mechanismen und Unterschiede", shared: "Gemeinsame Begriffe", differences: "Belegte Unterschiede", support: "Personen und Unterstützung", resources: "Studien, Ressourcen und Förderung", gaps: "Fehlende Belege", unknown: "Nicht erfasst", checked: "Abgerufen", status: "Erfasster Status", holder: "Verantwortliche Stelle", role: "Rolle", affiliation: "Institution", sponsor: "Sponsor", country: "Land", year: "Jahr", journal: "Zeitschrift", access: "Zugang", licence: "Lizenz", mechanism: "Mechanismus", biomarker: "Biomarker", symptom: "Symptom", funding: "Förderung ansehen", experiment: "Entwurf für ein gemeinsames Experiment erstellen", relatedSupport: "Verwandte Unterstützung", order: "Zurückgegebene Datensätze", noRanking: "Die Ergebnisposition allein belegt weder Mechanismusstärke noch ungedeckten Bedarf oder Ressourcenzugang.", empty: "Für diesen Bezug wurden keine konkreten Datensätze zurückgegeben.", reuse: "Eignung, Rechte und Validierung müssen für die Wiederverwendung bestätigt werden.", viewResource: "Ressource ansehen",
  },
};
