//! PROV-O for every state change (D10).
//!
//! Each version of a contribution is a `prov:Entity` (`contrib:<id>/v<n>`). Each change is a
//! `prov:Activity` (submission, auto-check, review) associated with its agent (the contributor, the
//! checking software, the reviewer), which `prov:used` the previous version (and, for checks, the
//! fetched pages with their SHA-256) and generated the next version. An AI assistant that found
//! the lead is a `prov:SoftwareAgent` that `prov:actedOnBehalfOf` the contributor.

use serde::{Deserialize, Serialize};
use serde_json::{Value, json};
use sha2::{Digest, Sha256};

use crate::model::{Agent, Contribution, State, entity_id};

/// One recorded state change.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProvEvent {
    pub contribution: String,
    /// `activity:contrib/<id>/<n>-<type>`.
    pub activity: String,
    /// `submission`, `auto_check`, `review`.
    pub activity_type: String,
    pub agent: Agent,
    /// Further agents involved (an assistant acting on behalf of the contributor).
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub delegates: Vec<Agent>,
    pub started_at: String,
    pub ended_at: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub from_state: Option<State>,
    pub to_state: State,
    /// Entities used, as JSON-LD nodes (`@id` at least).
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub used: Vec<Value>,
    /// The version this activity generated.
    pub generated: String,
    /// Hash of the exact compact public JSON receipt generated by this activity.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub generated_sha256: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub note: Option<String>,
}

impl ProvEvent {
    /// The event for a change that turned `before` (if any) into `after`.
    pub fn new(
        activity_type: &str,
        agent: Agent,
        before: Option<&Contribution>,
        after: &Contribution,
        started_at: String,
    ) -> Self {
        let mut used = Vec::new();
        if let Some(b) = before {
            used.push(json!({ "@id": b.entity() }));
        }
        Self {
            contribution: after.id.clone(),
            activity: format!(
                "activity:contrib/{}/{}-{}",
                after.id,
                after.version,
                activity_type.replace('_', "-")
            ),
            activity_type: activity_type.into(),
            agent,
            delegates: Vec::new(),
            started_at,
            ended_at: after.updated_at.clone(),
            from_state: before.map(|b| b.state),
            to_state: after.state,
            used,
            generated: after.entity(),
            generated_sha256: Some(format!(
                "{:x}",
                Sha256::digest(serde_json::to_vec(&after.public()).expect("public contribution serializes"))
            )),
            note: None,
        }
    }

    pub fn using(mut self, entity: Value) -> Self {
        self.used.push(entity);
        self
    }

    pub fn note(mut self, note: impl Into<String>) -> Self {
        self.note = Some(note.into());
        self
    }

    pub fn delegate(mut self, agent: Agent) -> Self {
        self.delegates.push(agent);
        self
    }
}

pub const CONTEXT: &str = "http://www.w3.org/ns/prov#";

/// JSON-LD document of a contribution's full history.
pub fn jsonld(c: &Contribution, events: &[ProvEvent]) -> Value {
    let mut graph: Vec<Value> = Vec::new();
    let mut agents: Vec<Value> = Vec::new();
    let mut add_agent = |a: &Agent, on_behalf_of: Option<&str>| {
        if agents.iter().any(|x| x["@id"] == a.id) {
            return;
        }
        let mut node = json!({ "@id": a.id, "@type": a.kind });
        if let Some(l) = &a.label {
            node["rdfs:label"] = json!(l);
        }
        if let Some(p) = on_behalf_of {
            node["prov:actedOnBehalfOf"] = json!({ "@id": p });
        }
        agents.push(node);
    };
    let mut entities: Vec<Value> = Vec::new();
    for e in events {
        add_agent(&e.agent, None);
        for d in &e.delegates {
            add_agent(d, Some(&e.agent.id));
        }
        let mut activity = json!({
            "@id": e.activity,
            "@type": "prov:Activity",
            "rdfs:label": e.activity_type,
            "prov:startedAtTime": { "@value": e.started_at, "@type": "xsd:dateTime" },
            "prov:endedAtTime": { "@value": e.ended_at, "@type": "xsd:dateTime" },
            "prov:wasAssociatedWith": std::iter::once(&e.agent).chain(&e.delegates).map(|a| json!({ "@id": a.id })).collect::<Vec<_>>(),
            "prov:used": e.used.iter().map(|u| json!({ "@id": u["@id"] })).collect::<Vec<_>>(),
            "prov:qualifiedUsage": e.used.iter().map(|u| json!({"@type": "prov:Usage", "prov:entity": {"@id": u["@id"]}, "prov:hadRole": {"@id": "role:contribution-evidence"}})).collect::<Vec<_>>(),
            "from_state": e.from_state,
            "to_state": e.to_state,
        });
        if let Some(n) = &e.note {
            activity["rdfs:comment"] = json!(n);
        }
        graph.push(activity);
        // Used entities that are not versions of this contribution (fetched pages, evidence URLs).
        for u in &e.used {
            let id = u["@id"].as_str().unwrap_or_default();
            if !id.starts_with("contrib:") {
                if let Some(existing) = entities.iter_mut().find(|x| x["@id"] == u["@id"]) {
                    if let (Some(existing), Some(extra)) = (existing.as_object_mut(), u.as_object()) {
                        for (key, value) in extra {
                            existing.entry(key.clone()).or_insert_with(|| value.clone());
                        }
                    }
                } else {
                    entities.push(u.clone());
                }
            }
        }
        let version = e
            .generated
            .rsplit("/v")
            .next()
            .and_then(|v| v.parse::<u32>().ok())
            .unwrap_or(0);
        let mut entity = json!({
            "@id": e.generated,
            "@type": "prov:Entity",
            "prov:wasGeneratedBy": { "@id": e.activity },
            "prov:generatedAtTime": { "@value": e.ended_at, "@type": "xsd:dateTime" },
            "prov:specializationOf": { "@id": format!("contrib:{}", c.id) },
            "state": e.to_state,
            "version": version.to_string(),
            "record_locator": e.generated,
            "source_url": format!("/api/contribute/{}", c.id),
            "retrieved_at": e.ended_at,
        });
        if let Some(hash) = &e.generated_sha256 {
            entity["sha256"] = json!(hash);
        }
        if version > 1 {
            entity["prov:wasRevisionOf"] = json!({ "@id": entity_id(&c.id, version - 1) });
            entity["prov:wasDerivedFrom"] = json!({"@id": entity_id(&c.id, version - 1)});
            entity["prov:qualifiedDerivation"] = json!({"@type": "prov:Derivation", "prov:entity": {"@id": entity_id(&c.id, version - 1)}, "prov:hadActivity": {"@id": e.activity}});
        }
        if e.activity_type == "submission" {
            entity["prov:wasAttributedTo"] = json!({ "@id": e.agent.id });
        }
        graph.push(entity);
    }
    graph.push(json!({
        "@id": format!("contrib:{}", c.id),
        "@type": "prov:Entity",
        "rdfs:label": format!("contribution {} ({})", c.id, c.kind.as_str()),
        "user_asserted": true,
        "state": c.state,
    }));
    graph.extend(entities);
    graph.extend(agents);
    json!({
        "@context": {
            "prov": CONTEXT,
            "rdfs": "http://www.w3.org/2000/01/rdf-schema#",
            "xsd": "http://www.w3.org/2001/XMLSchema#",
        },
        "@graph": graph,
    })
}

/// A web page as a PROV entity (what a check fetched, or an evidence URL as given).
pub fn page_entity(url: &str, sha256: Option<&str>, retrieved_at: Option<&str>, status: Option<u16>) -> Value {
    let id = match sha256 {
        Some(h) => format!(
            "page:sha256/{h}/snapshot/{:x}",
            Sha256::digest(format!("{url}|{}", retrieved_at.unwrap_or_default()).as_bytes())
        ),
        None => url.to_string(),
    };
    let mut v = json!({ "@id": id, "@type": "prov:Entity", "prov:atLocation": url });
    if let Some(h) = sha256 {
        v["sha256"] = json!(h);
    }
    if let Some(t) = retrieved_at {
        v["retrieved_at"] = json!(t);
        v["version"] = json!(format!("retrieval snapshot {t}"));
        v["record_locator"] = json!("whole response; check locators address the first 65536 bytes");
    }
    if let Some(s) = status {
        v["http_status"] = json!(s);
    }
    v
}
