//! Bounded, deterministic adjacency reads against the operator-configured nrese store.
use atlas_core::graph::Relation;
use futures_util::StreamExt;
use serde::Serialize;
use serde_json::Value;
use std::{collections::BTreeSet, sync::OnceLock, time::Duration};
use tokio::sync::Semaphore;

const BASE: &str = "https://w3id.org/rare-disease-atlas/";
const MAX_BYTES: usize = 1024 * 1024;
pub const MAX_ROWS: usize = 160;
static GATE: Semaphore = Semaphore::const_new(2);
static CLIENT: OnceLock<reqwest::Client> = OnceLock::new();

#[derive(Debug, Clone, Serialize, PartialEq, Eq)]
pub struct SparqlTriple {
    pub from: String,
    pub relation: String,
    pub to: String,
}
#[derive(Debug, Serialize)]
pub struct SparqlResult {
    pub query: String,
    pub queries: Vec<SparqlReceipt>,
    pub truncated: bool,
    pub triples: Vec<SparqlTriple>,
}
#[derive(Debug, Serialize)]
pub struct SparqlReceipt {
    pub seed_ids: Vec<String>,
    pub sparql: String,
    pub row_count: usize,
    pub row_cap: usize,
    pub reasoning: bool,
}

/// Exact atlas-release RDF mapping: percent-encode every non-unreserved UTF-8 byte.
pub fn node_iri(id: &str) -> String {
    let mut iri = format!("{BASE}id/");
    for b in id.bytes() {
        if b.is_ascii_alphanumeric() || b"-._~".contains(&b) {
            iri.push(b as char);
        } else {
            iri.push_str(&format!("%{b:02X}"));
        }
    }
    iri
}

pub fn iri_to_id(iri: &str) -> Option<String> {
    let encoded = iri.strip_prefix(&format!("{BASE}id/"))?;
    let mut bytes = Vec::new();
    let mut i = 0;
    while i < encoded.len() {
        if encoded.as_bytes()[i] == b'%' {
            let hex = encoded.get(i + 1..i + 3)?;
            bytes.push(u8::from_str_radix(hex, 16).ok()?);
            i += 3;
        } else {
            bytes.push(encoded.as_bytes()[i]);
            i += 1;
        }
    }
    let id = String::from_utf8(bytes).ok()?;
    // Only identifiers generated by the release mapping are accepted.
    (node_iri(&id) == iri).then_some(id)
}

fn allowed_relations() -> BTreeSet<&'static str> {
    Relation::ALL
        .into_iter()
        .map(Relation::as_str)
        .chain([
            atlas_journeys::GENE_RELATION,
            atlas_journeys::phenotype_relation(false),
            atlas_journeys::phenotype_relation(true),
        ])
        .collect()
}

pub fn compile_query(seeds: &[String], relations: &[String], limit: usize) -> Result<String, String> {
    if seeds.is_empty() || seeds.len() > 16 || seeds.iter().any(|s| s.is_empty() || s.len() > 256) {
        return Err("SPARQL requires 1 to 16 bounded seed identifiers".into());
    }
    let allowed = allowed_relations();
    if relations.len() > allowed.len() {
        return Err("Too many SPARQL relations".into());
    }
    let selected: BTreeSet<&str> = if relations.is_empty() {
        allowed.clone()
    } else {
        relations
            .iter()
            .map(|r| {
                allowed
                    .get(r.as_str())
                    .copied()
                    .ok_or_else(|| "Unknown SPARQL relation".to_owned())
            })
            .collect::<Result<_, _>>()?
    };
    let ids = seeds
        .iter()
        .map(|s| format!("<{}>", node_iri(s)))
        .collect::<BTreeSet<_>>()
        .into_iter()
        .collect::<Vec<_>>();
    // A literal seed binds the SPO/OSP index before predicate filtering. In nrese,
    // seed VALUES alone can leave the triple scan unbound; use actual constants.
    let predicates = selected
        .into_iter()
        .map(|r| format!("ra:{r}"))
        .collect::<Vec<_>>()
        .join(" ");
    let branches = ids
        .into_iter()
        .flat_map(|id| {
            [
                format!("  {{ {id} ?p ?o . BIND({id} AS ?s) }}"),
                format!("  {{ ?s ?p {id} . BIND({id} AS ?o) }}"),
            ]
        })
        .collect::<Vec<_>>()
        .join("\n  UNION\n");
    Ok(format!(
        "PREFIX ra: <{BASE}vocab#>\nSELECT DISTINCT ?s ?p ?o WHERE {{\n  VALUES ?p {{ {predicates} }}\n  {{\n{branches}\n  }}\n}}\nLIMIT {}",
        limit.clamp(1, MAX_ROWS)
    ))
}

/// Split only at constant-seed branch boundaries. Every receipt independently
/// satisfies the editor's byte cap; the sum of batch row budgets is bounded.
fn compile_batches(
    seeds: &[String],
    relations: &[String],
    limit: usize,
) -> Result<Vec<(Vec<String>, String, usize)>, String> {
    compile_query(seeds, relations, limit)?;
    let mut groups: Vec<Vec<String>> = Vec::new();
    for seed in seeds.iter().cloned().collect::<BTreeSet<_>>() {
        let mut candidate = groups.last().cloned().unwrap_or_default();
        candidate.push(seed.clone());
        if compile_query(&candidate, relations, MAX_ROWS)?.len() > 16 * 1024 {
            if candidate.len() == 1 {
                return Err("One neighborhood seed exceeds the query byte cap".into());
            }
            groups.push(vec![seed]);
        } else if let Some(last) = groups.last_mut() {
            *last = candidate;
        } else {
            groups.push(candidate);
        }
    }
    let cap = limit.clamp(1, MAX_ROWS);
    if groups.len() > cap {
        return Err("Neighborhood batch count exceeds the row budget".into());
    }
    let count = groups.len();
    groups
        .into_iter()
        .enumerate()
        .map(|(i, group)| {
            let rows = cap / count + usize::from(i < cap % count);
            let query = compile_query(&group, relations, rows)?;
            if query.len() > 16 * 1024 {
                return Err("Neighborhood query byte cap exceeded".into());
            }
            Ok((group, query, rows))
        })
        .collect()
}

fn decode_results(
    bytes: &[u8],
    seeds: &[String],
    relations: &[String],
    limit: usize,
) -> Result<Vec<SparqlTriple>, String> {
    let data: Value = serde_json::from_slice(bytes).map_err(|_| "Invalid SPARQL response".to_owned())?;
    let rows = data["results"]["bindings"]
        .as_array()
        .ok_or("Invalid SPARQL SELECT response")?;
    if rows.len() > limit.clamp(1, MAX_ROWS) {
        return Err("SPARQL row cap exceeded".into());
    }
    let mut triples = Vec::new();
    let mut seen = BTreeSet::new();
    for row in rows {
        let uri = |name: &str| -> Option<&str> {
            (row[name]["type"].as_str()? == "uri")
                .then(|| row[name]["value"].as_str())
                .flatten()
        };
        let Some((from, relation, to)) = uri("s")
            .and_then(iri_to_id)
            .zip(
                uri("p")
                    .and_then(|p| p.strip_prefix(&format!("{BASE}vocab#")))
                    .and_then(|r| allowed_relations().get(r).copied()),
            )
            .zip(uri("o").and_then(iri_to_id))
            .map(|((s, p), o)| (s, p.to_owned(), o))
        else {
            continue;
        };
        if !seeds.contains(&from) && !seeds.contains(&to) {
            return Err("SPARQL returned an unbound edge".into());
        }
        if !relations.is_empty() && !relations.contains(&relation) {
            return Err("SPARQL returned an unexpected relation".into());
        }
        if seen.insert((from.clone(), relation.clone(), to.clone())) {
            triples.push(SparqlTriple { from, relation, to });
        }
    }
    Ok(triples)
}

/// None means no store configured. A configured store failure is an explicit error.
pub async fn execute(seeds: &[String], relations: &[String], limit: usize) -> Result<Option<SparqlResult>, String> {
    let endpoint = match std::env::var("ATLAS_SPARQL_URL") {
        Ok(value) if !value.trim().is_empty() => value,
        _ => return Ok(None),
    };
    let batches = compile_batches(seeds, relations, limit)?;
    let url = reqwest::Url::parse(&endpoint).map_err(|_| "Invalid SPARQL server configuration")?;
    if !matches!(url.scheme(), "http" | "https")
        || url.host_str().is_none()
        || !url.username().is_empty()
        || url.password().is_some()
        || url.fragment().is_some()
    {
        return Err("Invalid SPARQL server configuration".into());
    }
    let _permit = GATE.try_acquire().map_err(|_| "SPARQL capacity reached")?;
    if CLIENT.get().is_none() {
        let client = reqwest::Client::builder()
            .timeout(Duration::from_secs(10))
            .connect_timeout(Duration::from_secs(3))
            .redirect(reqwest::redirect::Policy::none())
            .build()
            .map_err(|_| "SPARQL client unavailable")?;
        let _ = CLIENT.set(client);
    }
    let (queries, triples) = tokio::time::timeout(Duration::from_secs(12), async {
        let mut receipts = Vec::new();
        let mut all = Vec::new();
        for (batch_seeds, query, rows) in batches {
            let response = CLIENT
                .get()
                .expect("client initialized")
                .post(url.clone())
                .query(&[("infer", "false")])
                .header("accept", "application/sparql-results+json")
                .header("content-type", "application/sparql-query")
                .body(query.clone())
                .send()
                .await
                .map_err(|_| "SPARQL store unavailable".to_owned())?;
            if !response.status().is_success() {
                return Err(format!("SPARQL store returned HTTP {}", response.status().as_u16()));
            }
            if response.content_length().is_some_and(|n| n > MAX_BYTES as u64) {
                return Err("SPARQL byte cap exceeded".into());
            }
            let mut bytes = Vec::new();
            let mut stream = response.bytes_stream();
            while let Some(chunk) = stream.next().await {
                let chunk = chunk.map_err(|_| "SPARQL response interrupted".to_owned())?;
                if bytes.len() + chunk.len() > MAX_BYTES {
                    return Err("SPARQL byte cap exceeded".into());
                }
                bytes.extend_from_slice(&chunk);
            }
            let triples = decode_results(&bytes, &batch_seeds, relations, rows)?;
            receipts.push(SparqlReceipt {
                seed_ids: batch_seeds,
                sparql: query,
                row_count: triples.len(),
                row_cap: rows,
                reasoning: false,
            });
            all.extend(triples);
        }
        all.sort_by(|a, b| (&a.from, &a.relation, &a.to).cmp(&(&b.from, &b.relation, &b.to)));
        all.dedup();
        Ok::<_, String>((receipts, all))
    })
    .await
    .map_err(|_| "SPARQL store timed out".to_owned())??;
    Ok(Some(SparqlResult {
        query: queries[0].sparql.clone(),
        truncated: queries.iter().any(|receipt| receipt.row_count >= receipt.row_cap),
        queries,
        triples,
    }))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    #[ignore = "requires configured actual nrese release store"]
    async fn live_nrese_retrieves_bound_stxbp1_assertions() {
        let result = execute(&["HGNC:11444".into()], &[atlas_journeys::GENE_RELATION.into()], 40)
            .await
            .expect("actual nrese SELECT succeeds")
            .expect("store configured");
        assert!(
            !result.triples.is_empty(),
            "the loaded release must contain STXBP1 assertions"
        );
        assert!(
            result
                .triples
                .iter()
                .all(|triple| triple.to == "HGNC:11444" || triple.from == "HGNC:11444")
        );
        assert!(
            result
                .triples
                .iter()
                .all(|triple| triple.relation == atlas_journeys::GENE_RELATION)
        );
        assert!(result.triples.len() <= 40);
    }
    fn compiler_schema() -> atlas_ask::query::SchemaCard {
        use atlas_ask::query::{SchemaCard, schema::Lineage};
        SchemaCard {
            schema_version: 1,
            activity: serde_json::json!({"synthetic":true}),
            graph: Lineage {
                source_url: "urn:test:compiler".into(),
                retrieved_at: "2026-10-04T00:00:00Z".into(),
                version: "fixture".into(),
                sha256: "fixture".into(),
                record_locator: "explore_sparql.rs".into(),
            },
            statements: 0,
            classes: Default::default(),
            predicates: allowed_relations()
                .into_iter()
                .map(|r| (format!("{BASE}vocab#{r}"), Default::default()))
                .collect(),
            known_absent: Default::default(),
            prefixes: Default::default(),
            semantic_units: Default::default(),
            provenance_pattern: String::new(),
        }
    }
    #[test]
    fn actual_newline_compiler_receipts_are_guarded_unchanged_and_byte_bounded() {
        let scope: Vec<String> = [
            "about_condition",
            "about_gene",
            "author_of",
            "gene_associated_with_condition",
            "has_associated_gene",
            "model_of",
            "names_gene",
            "principal_investigator_of",
            "resource_for",
            "serves_condition",
            "serves_gene",
            "studied_for",
            "studies_condition",
            "targets",
        ]
        .into_iter()
        .map(str::to_owned)
        .collect();
        let seeds: Vec<String> = (0..16).map(|n| format!("PMID:{}", 42573089 + n)).collect();
        let actual = compile_query(&seeds, &scope, 160).unwrap();
        assert!(
            actual.len() < 16 * 1024,
            "actual fourteen-relation frontier is {} bytes",
            actual.len()
        );
        assert!(actual.contains("\nLIMIT 160"));
        assert_eq!(
            atlas_ask::query::guard::checked(&actual, &compiler_schema(), 160).unwrap(),
            actual
        );
        let worst: Vec<String> = (0..16).map(|n| format!("{}{}", "?".repeat(126), n)).collect();
        let batches = compile_batches(&worst, &[], 160).unwrap();
        assert!(batches.len() > 1);
        assert_eq!(batches.iter().map(|(_, _, rows)| rows).sum::<usize>(), 160);
        for (_, query, rows) in batches {
            assert!(query.len() <= 16 * 1024);
            assert_eq!(
                atlas_ask::query::guard::checked(&query, &compiler_schema(), rows).unwrap(),
                query
            );
        }
        assert!(atlas_ask::query::guard::checked(&actual, &compiler_schema(), 100).is_err());
    }
    #[test]
    fn release_iri_round_trip() {
        for id in ["MONDO:0001234", "HGNC:123", "org:a b", "x:é", "a%20b"] {
            assert_eq!(iri_to_id(&node_iri(id)).as_deref(), Some(id));
        }
        assert!(iri_to_id("https://evil.example/id/a").is_none());
        assert!(iri_to_id(&format!("{BASE}id/%GG")).is_none());
    }
    #[test]
    fn compiler_is_bounded_and_injection_safe() {
        assert!(
            compile_query(
                &["HGNC:1".into()],
                &["has_associated_gene".into(), "lacks_phenotype".into()],
                20
            )
            .unwrap()
            .contains("ra:has_associated_gene")
        );
        let q = compile_query(
            &["a> } SERVICE <https://evil> {".into()],
            &["targets".into()],
            usize::MAX,
        )
        .unwrap();
        assert!(q.ends_with("LIMIT 160"));
        assert!(!q.contains("?s ?p ?o ."));
        assert_eq!(q.matches("VALUES ?p").count(), 1);
        assert_eq!(q.matches("BIND(").count(), 2);
        assert!(!q.contains("SERVICE <"));
        assert!(q.contains("%3E%20%7D%20SERVICE"));
        assert!(compile_query(&["HGNC:1".into()], &["targets> }".into()], 20).is_err());
        assert!(compile_query(&[], &[], 20).is_err());
        assert!(compile_query(&vec!["a".into(); 17], &[], 20).is_err());
    }
    #[test]
    fn maps_only_bound_release_edges() {
        let row = serde_json::json!({"results":{"bindings":[{
            "s":{"type":"uri","value":node_iri("HGNC:1")},
            "p":{"type":"uri","value":format!("{BASE}vocab#targets")},
            "o":{"type":"uri","value":node_iri("MONDO:2")}
        }]}});
        let bytes = serde_json::to_vec(&row).unwrap();
        let result = decode_results(&bytes, &["MONDO:2".into()], &["targets".into()], 10).unwrap();
        assert_eq!(
            result[0],
            SparqlTriple {
                from: "HGNC:1".into(),
                relation: "targets".into(),
                to: "MONDO:2".into()
            }
        );
        assert!(decode_results(&bytes, &["MONDO:3".into()], &[], 10).is_err());
        assert!(decode_results(&bytes, &["MONDO:2".into()], &["held_by".into()], 10).is_err());
    }
}
