//! Catalog messages pending web integration in copy-audit deliverable 2.
use serde_json::{Value, json};

fn value(p: &Value, key: &str) -> String {
    match &p[key] {
        Value::String(s) => s.clone(),
        Value::Array(a) => a
            .iter()
            .map(|v| v.as_str().map(str::to_owned).unwrap_or_else(|| v.to_string()))
            .collect::<Vec<_>>()
            .join(", "),
        Value::Null => String::new(),
        Value::Object(o) => o.get("fallback").and_then(Value::as_str).unwrap_or_default().to_owned(),
        v => v.to_string(),
    }
}

pub fn msg(key: &str, p: Value) -> Value {
    let fallback = text(key, &p);
    json!({"key": key, "params": p, "fallback": fallback})
}

pub fn text(key: &str, p: &Value) -> String {
    match key {
        "ask.error.generic" => "Something went wrong. Please try again.".into(),
        "ask.error.context_too_large" => "Too much conversation context. Start a new conversation.".into(),
        "ask.list.more" => if p["remaining"].as_u64().unwrap_or(0) == 0 { value(p, "items") } else { format!("{} and {} more", value(p, "items"), value(p, "remaining")) },
        "ask.attribute.inheritance" => "Inheritance".into(),
        "ask.attribute.onset" => "Age at first symptoms".into(),
        "ask.prevalence.figure" => format!("Reported figure: {}", value(p, "value")),
        "ask.fragment.retrieved_date" => format!(", retrieved {}", value(p, "date")),
        "ask.need.groups" => "patient groups or expert centres".into(),
        "ask.need.studies" => "studies".into(),
        "ask.need.papers" => "papers".into(),
        "ask.need.grants" => "NIH research projects".into(),
        "ask.need.patient_group" => "patient group".into(),
        "ask.need.open_study" => "study or registry ongoing or planned".into(),
        "ask.need.researcher" => "researcher".into(),
        "ask.need.project" => "research project".into(),
        "ask.frequency.always" => "in all recorded cases".into(),
        "ask.frequency.very_often" => "in most recorded cases".into(),
        "ask.frequency.often" => "often".into(),
        "ask.frequency.sometimes" => "sometimes".into(),
        "ask.frequency.rarely" => "rarely".into(),
        "ask.frequency.not" => "in none of the recorded cases".into(),
        "ask.term.label" => if p["plain"].is_string() { format!("{} ({}; {})", value(p, "name"), value(p, "id"), value(p, "plain")) } else { format!("{} ({})", value(p, "name"), value(p, "id")) },
        "ask.kind.any" => "connections".into(),
        "ask.kind.study" => "study".into(),
        "ask.status.any" => "any recorded status".into(),
        "ask.status.open" => "ongoing or planned".into(),
        "ask.status.recruiting" => "recruiting".into(),
        "ask.status.closed" => "closed or not current".into(),
        "ask.assets.selection" => format!("{} assets, status: {}", value(p, "kind"), value(p, "status")),
        "ask.kind.trial" => "clinical trial".into(),
        "ask.kind.registry" => "patient registry".into(),
        "ask.kind.natural_history" => "natural history study".into(),
        "ask.kind.observational" => "observational study".into(),
        "ask.kind.expanded_access" => "expanded access programme".into(),
        "ask.kind.patient_group" => "patient group".into(),
        "ask.kind.expert_centre" => "expert centre".into(),
        "ask.kind.researcher" => "researcher".into(),
        "ask.kind.grant" => "research project".into(),
        "ask.kind.sponsor" => "study sponsor".into(),
        "ask.kind.institution" => "institution".into(),
        "ask.kind.organisation" => "organisation".into(),
        "ask.fragment.checked_date" => format!("; checked on {d}", d = value(p, "d")),
        "ask.fragment.countries" => format!("; countries: {arg0}", arg0 = value(p, "arg0")),
        "ask.fragment.sponsor" => format!("; sponsor: {arg0}", arg0 = value(p, "arg0")),
        "ask.fragment.country" => format!(" in {c}", c = value(p, "c")),
        "ask.fragment.description" => format!(": {d}", d = value(p, "d")),
        "ask.fragment.verified_date" => format!("; official channel verified on {d}", d = value(p, "d")),
        "ask.fragment.affiliation" => format!(", affiliation: {a}", a = value(p, "a")),
        "ask.fragment.funded_range" => format!(", funded {a}–{b}", a = value(p, "a"), b = value(p, "b")),
        "ask.fragment.funded_year" => format!(", funded {a}", a = value(p, "a")),
        "ask.fragment.paper_year" => format!(" ({y})", y = value(p, "y")),
        "ask.relation.studies_condition" => "is a study registered for".into(),
        "ask.relation.names_gene" => "names the gene".into(),
        "ask.relation.about_gene" => "is about the gene".into(),
        "ask.relation.about_condition" => "is about".into(),
        "ask.relation.author_of" => "is an author of".into(),
        "ask.relation.principal_investigator_of" => "leads".into(),
        "ask.relation.sponsored_by" => "is sponsored by".into(),
        "ask.relation.awarded_to" => "was awarded to".into(),
        "ask.relation.serves_condition" => "serves people with".into(),
        "ask.relation.serves_gene" => "serves people with changes in".into(),
        "ask.relation.same_as" => "is the same person as".into(),
        "ask.relation.held_by" => "is held by".into(),
        "ask.relation.model_of" => "is a research model of".into(),
        "ask.relation.studied_for" => "is being developed or studied for".into(),
        "ask.relation.targets" => "targets the gene".into(),
        "ask.relation.resource_for" => "is a research resource for".into(),
        "ask.relation.funds" => "funds research on".into(),
        "ask.relation.claims_about" => "states (extracted, quote-checked) something about".into(),
        "ask.relation.has_phenotype" => "has the feature".into(),
        "ask.relation.orthologous_to" => "is the matching gene of".into(),
        "ask.relation.gene_associated_with_condition" => "is linked to".into(),
        "ask.relation.candidate_same_as" => "is possibly the same as".into(),
        "ask.relation.related_to" => "is related to".into(),
        "ask.fragment.match_reason" => format!(" [matched by {reason}]", reason = value(p, "reason")),
        "ask.fact.gene_identity" => format!("{} ({}) is the gene '{}'.{}", value(p, "gene"), value(p, "id"), value(p, "name"), if p["aliases"].as_array().is_some_and(|a| !a.is_empty()) { format!(" Other recorded symbols: {}.", value(p, "aliases")) } else { String::new() }),
        "ask.fact.related_shared_symptoms" => format!("{} ({}) shares {} recorded symptoms with {}: {}.{}", value(p, "condition"), value(p, "id"), value(p, "count"), value(p, "query"), value(p, "symptoms"), if p["shared_gene"] == true { " These conditions also share a linked gene." } else { "" }),
        "ask.note.corrected_spelling" => format!("No direct match was found. Searched the corrected spelling '{fixed}'", fixed = value(p, "fixed")),
        "ask.note.genes_shown" => format!("{arg0} genes linked in total; 6 shown", arg0 = value(p, "arg0")),
        "ask.note.symptoms_shown" => format!("{arg0} symptoms recorded; 8 shown", arg0 = value(p, "arg0")),
        "ask.note.source_unloaded" => format!("We could not check {source} for {what} because this source is unavailable", what = value(p, "what"), source = value(p, "source")),
        "ask.note.exact_connection" => format!("At least one directly linked {what} was found", what = value(p, "what")),
        "ask.note.broader_groups" => format!("{related} patient groups for broader conditions are listed under connections", related = value(p, "related")),
        "ask.note.links_shown" => "10 links are shown. More are recorded".into(),
        "ask.note.conditions_shown" => format!("{arg0} conditions linked to {arg1}; 8 shown", arg0 = value(p, "arg0"), arg1 = value(p, "arg1")),
        "ask.note.shared_researchers" => format!("{arg0} researchers for {la}, {arg1} for {lb}, {arg2} shared; {arg3} shown", arg0 = value(p, "arg0"), la = value(p, "la"), arg1 = value(p, "arg1"), lb = value(p, "lb"), arg2 = value(p, "arg2"), arg3 = value(p, "arg3")),
        "ask.note.counts" => format!("{arg0} {what} found ({exact} linked to the condition or its gene directly, {arg1} through a broader group or a multi-gene link); {shown} shown, strongest first", arg0 = value(p, "arg0"), what = value(p, "what"), exact = value(p, "exact"), arg1 = value(p, "arg1"), shown = value(p, "shown")),
        "ask.note.gene_conditions" => format!("{arg0} other conditions share {arg1}; 5 shown", arg0 = value(p, "arg0"), arg1 = value(p, "arg1")),
        "ask.note.symptom_threshold" => format!("No condition met the search threshold of {MIN_SHARED} shared uncommon symptoms with {arg0}", MIN_SHARED = value(p, "MIN_SHARED"), arg0 = value(p, "arg0")),
        "ask.note.cause_comparison_unavailable" => "The recorded causes could not be compared for these results. Shared symptoms alone do not establish a shared cause".into(),
        "ask.note.gene_results" => format!("{arg0} conditions linked to {arg1}; {arg2} shown", arg0 = value(p, "arg0"), arg1 = value(p, "arg1"), arg2 = value(p, "arg2")),
        "ask.note.process_unavailable" => format!("We could not search for '{process}' because the Reactome and Gene Ontology process records are unavailable", process = value(p, "process")),
        "ask.note.no_path" => format!("No recorded chain of at most {MAX_DEPTH} links connects {arg0} and {arg1}", MAX_DEPTH = value(p, "MAX_DEPTH"), arg0 = value(p, "arg0"), arg1 = value(p, "arg1")),
        "ask.note.path_length" => format!("Shortest recorded chain: {arg0} links", arg0 = value(p, "arg0")),
        "ask.fact.recorded_symptom" => format!("{arg0} ({arg1}) has {arg2}", arg0 = value(p, "arg0"), arg1 = value(p, "arg1"), arg2 = value(p, "arg2")),
        "ask.fact.symptom_conditions" => format!("{arg0} conditions in the atlas list {term} or a more specific form of it", arg0 = value(p, "arg0"), term = value(p, "term")),
        "ask.fact.gene_condition_link" => format!("{symbol} is linked to {arg0}", symbol = value(p, "symbol"), arg0 = value(p, "arg0")),
        "ask.chip.invalid" => "This task could not run. Check its required search terms and record IDs.".into(),
        "ask.response.planning_fallback" => "The assistant could not choose search tasks. Zebratlas used keyword matches instead.".into(),
        "ask.response.save_failed" => "This conversation could not be saved. Copy it before leaving this page.".into(),
        "ask.template.no_result" => "No sourced result was found for this task. Review the search terms or try another task.".into(),
        "ask.template.no_facts" => "Zebratlas has no sourced information for this question.".into(),
        "ask.error.empty_question" => "Enter a question or choose a search task.".into(),
        "ask.error.question_too_long" => format!("Keep your question to {} characters or fewer.", value(p, "limit")),
        "ask.coverage.source_unloaded" => format!("We could not check {arg0}. Source status: {arg1}", arg0 = value(p, "arg0"), arg1 = value(p, "arg1")),
        "ask.coverage.gene_subset" => format!("{arg0} was searched for these genes: {arg1}. {arg3} was outside that search, so its {what} remain unchecked", arg0 = value(p, "arg0"), arg1 = value(p, "arg1"), what = value(p, "what"), arg3 = value(p, "arg3")),
        "ask.coverage.none_found" => format!("No {what} linked to {arg0} ({arg1}) or its gene was found in {arg2} (searched: {arg3}{when})", what = value(p, "what"), arg0 = value(p, "arg0"), arg1 = value(p, "arg1"), arg2 = value(p, "arg2"), arg3 = value(p, "arg3"), when = value(p, "when")),
        "ask.fact.symptom_frequency" => format!("{name} has {term}: reported {arg0} (frequency {raw})", name = value(p, "name"), term = value(p, "term"), arg0 = value(p, "arg0"), raw = value(p, "raw")),
        "ask.fact.symptom_possible" => format!("{name} can include {term}", name = value(p, "name"), term = value(p, "term")),
        "ask.fact.matched_record" => format!("'{text}' matches the {arg0} {arg1} ({arg2}) by its {how} \"{matched}\"", text = value(p, "text"), arg0 = value(p, "arg0"), arg1 = value(p, "arg1"), arg2 = value(p, "arg2"), how = value(p, "how"), matched = value(p, "matched")),
        "ask.fact.candidate_condition" => format!("Suggested condition for '{text}': {arg0} ({arg1})", text = value(p, "text"), arg0 = value(p, "arg0"), arg1 = value(p, "arg1")),
        "ask.fact.definition" => format!("{name} ({id}): {arg0}", name = value(p, "name"), id = value(p, "id"), arg0 = value(p, "arg0")),
        "ask.fact.rare_classification" => format!("{name} ({id}) is classed as a rare disease", name = value(p, "name"), id = value(p, "id")),
        "ask.fact.synonyms" => format!("{name} is also called: {arg0}", name = value(p, "name"), arg0 = value(p, "arg0")),
        "ask.fact.attribute" => format!("{what} of {name}: {arg0}", what = value(p, "what"), name = value(p, "name"), arg0 = value(p, "arg0")),
        "ask.fact.prevalence" => format!("{arg0} of {name} ({arg1}): {value}", arg0 = value(p, "arg0"), name = value(p, "name"), arg1 = value(p, "arg1"), value = value(p, "value")),
        "ask.fact.connections_summary" => format!("For {name} or its gene, the sources checked list {studies} studies ({open} ongoing or planned) and {groups} patient groups or expert centres", studies = value(p, "studies"), name = value(p, "name"), open = value(p, "open"), groups = value(p, "groups")),
        "ask.fact.prevalence_missing" => format!("Orphanet records no figure for how common {name} ({id}) is", name = value(p, "name"), id = value(p, "id")),
        "ask.fact.causal_gene_missing" => format!("No causal gene for {name} ({id}) is recorded in Orphanet or OMIM", name = value(p, "name"), id = value(p, "id")),
        "ask.fact.symptoms_missing" => format!("The Human Phenotype Ontology records no symptoms for {name} ({id})", name = value(p, "name"), id = value(p, "id")),
        "ask.fact.record_definition" => format!("{arg0} ({arg1}): {arg2}", arg0 = value(p, "arg0"), arg1 = value(p, "arg1"), arg2 = value(p, "arg2")),
        "ask.fact.term_definition" => format!("{arg0}{def}", arg0 = value(p, "arg0"), def = value(p, "def")),
        "ask.fact.parent_condition" => format!("{label} ({cid}) is a kind of {anc_name} ({anc}) in the MONDO disease hierarchy", label = value(p, "label"), cid = value(p, "cid"), anc_name = value(p, "anc_name"), anc = value(p, "anc")),
        "ask.fact.study" => format!("{arg0} ({arg1}): {arg2}. Status: {arg3}{sponsor}{countries}{checked}", arg0 = value(p, "arg0"), arg1 = value(p, "arg1"), arg2 = value(p, "arg2"), arg3 = value(p, "arg3"), sponsor = value(p, "sponsor"), countries = value(p, "countries"), checked = value(p, "checked")),
        "ask.fact.organisation" => format!("{arg0}: {arg1}{place}{about}{verified}", arg0 = value(p, "arg0"), arg1 = value(p, "arg1"), place = value(p, "place"), about = value(p, "about"), verified = value(p, "verified")),
        "ask.fact.researcher" => format!("{arg0} is a researcher{aff}{checked}", arg0 = value(p, "arg0"), aff = value(p, "aff"), checked = value(p, "checked")),
        "ask.fact.grant" => format!("{arg0} ({arg1}) is an NIH-funded research project at {arg2}{years}", arg0 = value(p, "arg0"), arg1 = value(p, "arg1"), arg2 = value(p, "arg2"), years = value(p, "years")),
        "ask.fact.paper" => format!("{arg0} ({arg1}) is a paper in {arg2}{year}", arg0 = value(p, "arg0"), arg1 = value(p, "arg1"), arg2 = value(p, "arg2"), year = value(p, "year")),
        "ask.fact.gene_association" => format!("{arg0} ({arg1}) is a gene linked to {arg2} ({arg3}): {assoc} (source: {arg4})", arg0 = value(p, "arg0"), arg1 = value(p, "arg1"), arg2 = value(p, "arg2"), arg3 = value(p, "arg3"), assoc = value(p, "assoc"), arg4 = value(p, "arg4")),
        "ask.fact.recorded_relationship" => format!("{arg0} {arg1} {arg2}{reason}", arg0 = value(p, "arg0"), arg1 = value(p, "arg1"), arg2 = value(p, "arg2"), reason = value(p, "reason")),
        _ => panic!("unknown copy key: {key}"),
    }
}

/// Plain labels nested in coverage messages; no English phrases travel as parameters.
pub fn need(label: &str) -> Value {
    let kind = match label {
        "patient groups or expert centres" => "groups",
        "studies" => "studies",
        "papers" => "papers",
        "NIH research projects" => "grants",
        "patient group" => "patient_group",
        "open study or registry" => "open_study",
        "researcher" => "researcher",
        "research project" => "project",
        _ => panic!("unknown need label"),
    };
    msg(&format!("ask.need.{kind}"), json!({}))
}
